# ###################################
# # START OF ORIGINAL CONFIGURATION #
# ###################################
# # Git sync
# dags:
#   persistence:
#     # Enable persistent volume for storing dags
#     enabled: false
#     # Volume size for dags
#     size: 1Gi
#     # If using a custom storageClass, pass name here
#     storageClassName: nfs-client
#     # access mode of the persistentc

#   gitSync:
#     enabled: true
#     repo: https://github.com/DeleLinus/movie-analytics
#     branch: master
#     rev: HEAD
#     depth: 1
#     # the number of consecutive failures allowed before aborting
#     maxFailures: 0
#     # subpath within the repo where dags are located
#     # should be "" if dags are at repo root
#     subPath: "/airflow-gke/dags"


# logs:
#   persistence:
#     # Enable persistent volume for storing logs
#     enabled: false
#     # Volume size for logs
#     size: 1Gi
#     # If using a custom storageClass, pass name here
#     storageClassName: nfs-client

# ###################################
# ## END OF ORIGINAL CONFIGURATION ##
# ###################################



###################################
## COMPONENT | Triggerer
###################################
triggerer:
 ## if the airflow triggerer should be deployed
 ## - [WARNING] the triggerer component was added in airflow 2.2.0
 ## - [WARNING] if `airflow.legacyCommands` is `true` the triggerer will NOT be deployed
 ##
 enabled: false
###################################
## COMPONENT | Flower
###################################
flower:
 ## if the airflow flower UI should be deployed
 ##
 enabled: false
###################################
## CONFIG | Airflow Logs
###################################
logs:
 ## the airflow logs folder
 ##
 path: /usr/local/airflow/logs
 ## configs for the logs PVC
 ##
 persistence:
  ## if a persistent volume is mounted at `logs.path`
  ##
  enabled: false
###################################
## CONFIG | Airflow DAGs
###################################
dags:
 ## the airflow dags folder
 ##
#  path: /usr/local/airflow/dags
 ## configs for the git-sync sidecar (https://github.com/kubernetes/git-sync)
 ##
 gitSync:
  ## if the git-sync sidecar container is enabled
  ##
  enabled: true
  ## the url of the git repo
  ##
  ## ____ EXAMPLE _______________
  ##  # https git repo
  ##  repo: https://github.com/USERNAME/REPOSITORY.git”
  ##
  ## ____ EXAMPLE _______________
  ##  # ssh git repo
  ##  repo: “git@github.com:USERNAME/REPOSITORY.git”
  ##
  repo: https://github.com/DeleLinus/movie-analytics
  ## the sub-path within your repo where dags are located
  ## - only dags under this path within your repo will be seen by airflow,
  ##  (note, the full repo will still be cloned)
  ##
  repoSubPath: /airflow-gke/dags
  # subPath: /airflow-gke/dags
  ## the git branch to check out
  ##
  branch: master
###################################
## DATABASE | PgBouncer
###################################
pgbouncer:
 ## if the pgbouncer Deployment is created
 ##
 enabled: false